version: 2
updates:
  - package-ecosystem: 'npm'
    versioning-strategy: increase
    directory: '/'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
      - dependency-name: '@docusaurus*'
      - dependency-name: 'eslint*'
      - dependency-name: 'prettier*'
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
      - dependency-name: 'fs-extra'
