name: deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MODE: production
    steps:
      - uses: actions/checkout@v3
        with:
          # Needed for showLastUpdateTime to work
          fetch-depth: 0
      - name: Prepare Yarn
        uses: ./.github/actions/prepare/
      - name: Prepare build
        run: yarn prepare
        shell: bash
      - name: Checkout remote
        run: yarn checkout:remote
      - name: Generate API
        run: yarn generate:api
        shell: bash
      - name: Build
        run: yarn build
      # Convert to Vercel project and upload
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      # Trigger Algolia crawler
      - name: Crawl
        run: |
          curl -H "Content-Type: application/json" -X POST --user ${{ secrets.ALGOLIA_USER_ID }}:${{ secrets.ALGOLIA_API_KEY }} "https://crawler.algolia.com/api/1/crawlers/${{ secrets.ALGOLIA_CRAWLER_ID }}/run"
